name: Jupyterbook

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONDA_PREFIX: /usr/share/miniconda/
      GPAW_SETUP_PATH: /usr/share/miniconda/share/gpaw

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        environment-file: .github/ci_support/environment.yml
        auto-activate-base: false
    - name: Install Jupyterbook
      shell: bash -l {0}
      run: |
        pip install git+https://github.com/ExecutableBookProject/jupyter-book
        echo "- file: README.md" > _toc.yml
        echo "- file: intro_pyiron_building_blocks/intro.ipynb" >> _toc.yml
        echo "- file: customized_job/custom_python_job.ipynb" >> _toc.yml
        echo "- file: customized_job/custom_bash_job.ipynb" >> _toc.yml
        echo "- file: lammps_damask_workflow/lammps-damask-workflow.ipynb" >> _toc.yml
        echo "- file: data_mining/data_mining.ipynb" >> _toc.yml
        curl https://pyiron.org/images/logo_dark.png --output logo_dark.png
        bash .github/ci_support/write_book_config.sh
        rm CODE_OF_CONDUCT.md LICENSE
        rm -r Exercises
        jupyter-book build . --path-output public
    - run: mv public/_build/html public_html
    - run: touch public_html/.nojekyll
