name: Docker Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t materialdigital/pyiron_onboarding_workshop:latest .docker_image/
      - run: docker tag materialdigital/pyiron_onboarding_workshop:latest materialdigital/pyiron_onboarding_workshop:"$(date +%F)"
      - run: docker images
      - run: docker run --rm materialdigital/pyiron_onboarding_workshop:latest /bin/bash -c 'source /opt/conda/bin/activate; git clone https://github.com/materialdigital/PMD-workflow-workshop ${HOME}/workflow_onboarding_workshop; cd ${HOME}/workflow_onboarding_workshop; cp .ci_support/build_notebooks.sh .; chmod +x build_notebooks.sh; ./build_notebooks.sh'  
